astrology/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

from astro_app.views import HomeView, AboutView, ServisesView, ArticlesView, Article_View_info, FAQView, DoneView, \
    ReviewView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', HomeView.as_view()),
    path('about/', AboutView.as_view()),
    path('services/', ServisesView.as_view()),
    path('articles/', ArticlesView.as_view()),
    path('articles/<slug:slug>', Article_View_info.as_view(), name='article_detail'),
    path('done/', DoneView.as_view()),
    path('faq/', FAQView.as_view()),
    path('reviews/', ReviewView.as_view()),
)

astro_app/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from transliterate import translit
from ckeditor.fields import RichTextField


def latin_name(i):
    return translit(i, language_code='ru', reversed=True)


class Articles(models.Model):
    name = models.CharField(max_length=40)
    keywords = models.CharField(max_length=260, default='', null=False)
    description = models.CharField(max_length=260, default='', null=False, blank=True)
    text = RichTextField()
    slug = models.SlugField(default='', null=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(latin_name(self.name))
        super(Articles, self).save(*args, **kwargs)

    def get_url(self):
        return reverse("article_detail", args=[self.slug])

    def __str__(self):
        return f"{self.name} "


class Pages(models.Model):
    title = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    keywords = models.CharField(max_length=260, default='', null=False, blank=True)
    description = models.CharField(max_length=260, default='', null=False, blank=True)
    text = RichTextField(default='', null=False, blank=True)
    img_name = models.CharField(max_length=30, default='', null=False, blank=True)
    slug = models.SlugField(default='', null=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(latin_name(self.name))
        super(Pages, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"


class Reviews(models.Model):
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=40)
    message = models.TextField()

    def __str__(self):
        return f"{self.name} "


class Service(models.Model):
    name = models.CharField(max_length=40)
    short_text = models.CharField(max_length=400)
    keywords = models.CharField(max_length=260, default='', null=False, blank=True)
    description = models.CharField(max_length=260, default='', null=False, blank=True)
    text = RichTextField(default='', null=False, blank=True)
    slug = models.SlugField(default='', null=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(latin_name(self.name))
        super(Service, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

astro_app/forms.py
from django import forms
from .models import Reviews


class ReviewsForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['name', 'email', 'message']
        labels = {
            'name': 'Contact name',
            'email': 'Contact email',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'email'
            }),
            'message': forms.Textarea(attrs={'class': 'form-control'}),
        }

astro_app/views.py
from .models import Service, Reviews, Articles, Pages
from .forms import ReviewsForm
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView, CreateView


class ReviewView(CreateView):
    form_class = ReviewsForm
    model = Reviews
    template_name = 'astro_app/reviews.html'
    success_url = '../done/'
    extra_context = {'reviews': Reviews.objects.all().order_by('-id')}


class DoneView(ListView):
    template_name = "astro_app/done.html"
    model = Reviews
    context_object_name = 'reviews'

    def get_queryset(self):
        context = super().get_queryset()
        filter_qs = context.order_by('-id')
        return filter_qs


class HomeView(ListView):
    template_name = 'astro_app/home.html'
    model = Service
    context_object_name = 'service'


class FAQView(TemplateView):
    template_name = 'astro_app/faq.html'

    def get_context_data(self, **kwargs):
        context = super(FAQView, self).get_context_data(**kwargs)
        context["info"] = Pages.objects.get(id=4)
        return context


class AboutView(TemplateView):
    template_name = 'astro_app/about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context["info"] = Pages.objects.get(id=2)
        return context


class ServisesView(ListView):
    template_name = "astro_app/services.html"
    model = Service
    context_object_name = 'service'


class ArticlesView(ListView):
    template_name = "astro_app/articles.html"
    model = Articles
    context_object_name = 'articles'


class Article_View_info(DetailView):
    template_name = "astro_app/article_info.html"
    model = Articles
    context_object_name = 'article'

astro_app/templates/astro_app/about.html
{% extends 'index.html' %}

{% block title %}
    {{ info.name }}
{% endblock %}

{% block content %}
{{ info.text|safe }}
{% endblock %}

astro_app/templates/astro_app/article_info.html
{% extends 'index.html' %}
{% load i18n %}
{% load common_tags %}

{% block title %}
    {{ article.name }}
{% endblock %}
{% block keywords %}
    {{ article.keywords }}
{% endblock %}
{% block description %}
    {{ article.description }}
{% endblock %}

{% block content %}
    <h2><a href="/articles/">{% trans 'Все статьи' %}</a> | {{ article.name }}</h2>
    {{ article.text|safe }}
{% endblock %}

astro_app/templates/astro_app/articles.html
{% extends 'index.html' %}
{% load common_tags %}
{% block title %}
    {% info 5 %}
{% endblock %}

{% block content %}
    <h2>{% info 5 %}</h2>
{% endblock %}

{% block content2 %}
    {% include 'astro_app/articles_list.html' %}
{% endblock %}

astro_app/templates/astro_app/articles_list.html
    <div class="row">
    {% for item in articles %}

        <div class="col-sm-12 col-md-6 col-lg-12 col-xl-6 mb-4">
            <div class="media tm-bg-transparent-black tm-border-white">
                <div class="media-body">
                    <h3>{{ item.name }} </h3>
                    <p>
                        {{ item.text|safe|truncatechars:280 }}
                    </p>

                    <a href="{{  item.get_url }}" class="btn tm-btn tm-font-big" data-nav-link="#tmNavLink2">Читать далее</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>

astro_app/templates/astro_app/done.html
{% extends 'index.html' %}
{% load common_tags %}
{% load i18n %}

{% block title %}
    {% trans 'Отзыв отправлен' %}
{% endblock %}

{% block content %}

	<div class="row mb-4">
		<div class="col-sm-12">
			<header><h2 class="tm-text-shadow">{% trans 'Ваш отзыв отправлен' %}</h2></header>
		</div>
	</div>

{% endblock %}

{% block content2 %}
	{% include 'astro_app/reviews_list.html' %}
{% endblock %}

astro_app/templates/astro_app/faq.html
{% extends 'index.html' %}

{% block title %}
    {{ info.name }}
{% endblock %}

{% block content %}
    {{ info.text|safe }}
{% endblock %}

astro_app/templates/astro_app/home.html
{% extends 'index.html' %}
{% load common_tags %}
{% load i18n %}

{% block title %}
    {% trans 'Астролог Киев' %}
{% endblock %}

{% block description %}
    {% trans 'Астролог Киев, услуги астролога в  Киеве: составление натальной карты, индивидуальный гороскоп, личный прогноз на год' %}
{% endblock %}

{% block content %}
<h1 style="margin-bottom: 0">Astra inclinant,non necessitant</h1>
<h2>
    <small>{% trans 'астрология, гороскопы, будущее...' %}</small>
</h2>
<div class="entry">
<!--    <img class="left" style="border: 1px solid #0a3b63;" src="images/img.jpg" alt="" width="150" />-->

    <p><strong>{% trans 'Астрология' %}</strong> &ndash; {% trans 'одна из древнейших наук, доживших до наших дней, не потеряв свою значимость. С древних времён астрологи полагают, что будущее каждого обитателя Земли записано на небе расположением планет и других небесных светил в момент его рождения. Астрологический прогноз &ndash; это не только информация по вашему знаку зодиака на неделю, астрология занимается глубоким изучением устройства нашего мира и взаимосвязей в нем.</p><p>Человек, который впервые попадает на профессиональную астрологическую консультацию, окунается в новое измерение. Иногда информация, полученная в общении с астрологом, помогает не только лучше понять происходящее, расставить приоритеты и акценты, но иногда и существенно изменить «точку сборки» – т.е. те ценностные ориентиры, которые служат в жизни главными «маяками».' %}</p>

    <p>{% trans 'К примеру, Вы чувствуете «кризис среднего возраста». <strong><em>Профессия</em></strong>, которой Вы посвятили много лет, не приносит удовлетворения, кажется скучной и исчерпавшей себя. Но внутри есть ощущение (или томление): хочу что-то изменить, но не могу понять, в каком направлении двигаться… Обратитесь к астрологу, и он поможет Вам обнаружить потенциальные и ожидающие своего часа таланты и способности. Да-да, так бывает, что раньше Вы никак не могли заняться этим – просто потому, что время еще не пришло! Особый разговор: люди, у которых за профессию отвечают высшие планеты – Уран, Нептун, Плутон, в этом случае вообще очень важно, чтобы у человека за плечами был большой жизненный опыт, потому что справиться с «вибрациями» профессий такого рода очень сложно неопытному. И иногда именно от астролога Вы получите «добро» на профессию или род занятий, который окружающим может казаться малопривлекательной, трудно осуществимой. У Вас должно получиться, потому что именно в вашей натальной карте планеты предполагают редкие, особенные возможности в той или иной сфере.' %}</p>

    <p>{% trans 'В вопросах, связанных с <strong><em>анализом совместимости</em></strong>, на астрологической консультации тоже можно узнать много важного и интересного. Вы можете выяснить, какую роль играет тот или иной персонаж в вашей жизни, и по синастрии (гороскопу совместимости, который получается при наложении гороскопов друг на друга) с удивлением узнать, что один из близких людей, например, активизирует ваш Сатурн, и тем самым пришел в вашу жизни для того, чтобы выработать у Вас такие качества, как терпение, смирение, ответственность. И,как бы не хотелось Вам немного схалтурить, «замести мусор под коврик» – он Вам этого сделать не даст, не старайтесь! Представьте, если эту миссию «звезды» делегировали вашему ребенку: именно он будет «высшим арбитражным судьей» в вашей жизни. Но не всегда всё столь однозначно. Именно астрологический анализ позволяет понять, какие ваши ожидания от партнерских отношений, подходит ли под них ваш партнер, и возможно ли достичь гармонии в вашем союзе.' %}</p>

    <p>{% trans 'Большой потенциал у <strong><em>«детской» астрологии</em></strong>! Конечно, не обязательно бежать на консультацию к астрологу сразу после рождения ребенка, но примерно с 2-3 лет Вам стоит узнать о том, какие личностные особенности вашего крошки будут сами прокладывать себе дорогу, а какие нуждаются в коррекции, более тонком понимании и направлении  в нужное русло. Например, у вас родился малыш с Солнцем в Весах, и согласно традиционным астрологическим интерпретациям, он должен быть «белым и пушистым», а по факту – маленький чертенок! Возможно, подменили в роддоме??? Нет, что Вы! Просто у него восходящий знак, отвечающий за внешность и манеру поведения человека – в Скорпионе, и он добавит в вашу жизни ощутимую порцию перца! И, уж наверняка, Вам лучше быть к этому готовым!' %}</p>

    <p>{% trans 'Этим не исчерпываются возможности профессиональной астрологии. Вы можете решать с её помощью много различных проблем.' %}</p>

    <ul>
        <li>{% trans 'Ректификация времени рождения' %}</li>
        <li>{% trans 'Событийный прогноз на ближайший год' %}</li>
        <li>{% trans 'Формирование стратегии личностного развития' %}</li>
        <li>{% trans 'Определение особенностей совместимости и перспектив партнерства в бизнесе и браке' %}</li>
        <li>{% trans 'Выбор времени для лечения и оперативного вмешательства' %}</li>
        <li>{% trans 'Определение причин, затрудняющих зачатие детей' %}</li>
    </ul>


</div>
<!---->
{% endblock %}
{% block content2 %}
{% include 'astro_app/services_list.html' %}
{% endblock %}
<!---->

astro_app/templates/astro_app/reviews.html
{% extends 'index.html' %}
{% load common_tags %}
{% load i18n %}

{% block title %}
    {% info 3 %}
{% endblock %}

{% block content %}

	<div class="row mb-4">
		<div class="col-sm-12">
			<header><h2 class="tm-text-shadow">{% trans 'Написать отзыв' %}</h2></header>
		</div>
	</div>
	<div class="row tm-page-4-content">
		<div class="col-md-6 col-sm-12 tm-contact-col">
			<div class="contact_message">
				<form method="post" class="contact-form">
					{% csrf_token %}
					{{ form }}
					<br>
					<button type="submit" class="btn tm-btn-submit tm-btn ml-auto">{% trans 'Отправить' %}</button>
				</form>
			</div>
		</div>
		<div class="col-md-6 col-sm-12 tm-contact-col">
<!--			<div class="tm-address-box">-->
<!--				<p>Aliquam interdum, nisl sedd faucibus tempor, massa velit laoreet ipsum, et faucibus sapien magna at enim. Suspendisse a dictum tortor.</p>-->
<!--				<p>Curabitur venenatis leo in augue convallis, vulputate sollicitudin ex maximus.</p>-->
<!--				<address>-->
<!--					120-240 Aliquam nec neque augue<br>-->
<!--					Suspendisse tincidunt nunc,<br>-->
<!--					vitae sagis justo 11000-->
<!--				</address>-->
<!--			</div>-->
		</div>
	</div>


{% endblock %}

{% block content2 %}
	{% include 'astro_app/reviews_list.html' %}
{% endblock %}

astro_app/templates/astro_app/reviews_list.html
{% load common_tags %}
<div class="row mb-4">
    <header class="col-xl-12"><h2 class="tm-text-shadow">{% info 3 %}</h2></header>
</div>
<div class="row">
{% for review in reviews %}

    <div class="col-sm-12 col-md-6 col-lg-12 col-xl-6 mb-4">
        <div class="media tm-bg-transparent-black tm-border-white">
            <div class="media-body">
                <h3>{{ review.name }}</h3>
                <h3>{{ review.email }}</h3>
                <p>{{ review.message|title }}</p>
            </div>
        </div>
    </div>
{% endfor %}
</div>

astro_app/templates/astro_app/services.html
{% extends 'index.html' %}
{% load common_tags %}
{% block title %}
    {% info 1 %}
{% endblock %}

{% block content %}
    <h2>{% info 1 %}</h2>
{% endblock %}

{% block content2 %}
    {% include 'astro_app/services_list.html' %}
{% endblock %}

astro_app/templates/astro_app/services_list.html
    <div class="row">
    {% for item in service %}

        <div class="col-sm-12 col-md-6 col-lg-12 col-xl-6 mb-4">
            <div class="media tm-bg-transparent-black tm-border-white">
                <div class="media-body">
                    <h3>{{ item.name }}</h3>
                    <p>{{ item.short_text|title }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load i18n %}
{% load common_tags %}

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} {% endblock %}
    </title>
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
	<meta name="keywords" content="{% block keywords %}{% endblock %}">
	<meta name="description" content="{% block description %}{% endblock %}">
<!--        {% block add_css %} {% endblock %}-->

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
	<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'slick/slick-theme.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">

	<script>
		var renderPage = true;

	if(navigator.userAgent.indexOf('MSIE')!==-1
		|| navigator.appVersion.indexOf('Trident/') > 0){
   		/* Microsoft Internet Explorer detected in. */
   		alert("Please view this in a modern browser such as Chrome or Microsoft Edge.");
   		renderPage = false;
	}
	</script>

</head>
<body>
	<!-- Loader -->
	<div id="loader-wrapper">
		<div id="loader"></div>
		<div class="loader-section section-left"></div>
		<div class="loader-section section-right"></div>
	</div>

	<!-- Page Content -->
	<div class="container-fluid tm-main">
		<div class="row tm-main-row">
			{% show_menu %}

			<div class="col-xl-9 tm-content ">
				<div class="tm-bg-transparent-black tm-contact-box-pad">
					{% block content %}
					{% endblock %}
				</div>

				{% block content2 %}
				{% endblock %}
			</div>

		</div>
<!-- section 3 -->

<!--		<footer class="footer-link">-->
<!--			<p class="tm-copyright-text">-->
<!--				Copyright &copy; 2022 Berezko Anna-->
<!--			</p>-->
<!--		</footer>-->


		<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.backstretch.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script> <!-- Slick Carousel -->

		<script>

		var sidebarVisible = false;
		var currentPageID = "#tm-section-1";

		// Setup Carousel
		function setupCarousel() {

			// If current page isn't Carousel page, don't do anything.
			if($('#tm-section-2').css('display') == "none") {
			}
			else {	// If current page is Carousel page, set up the Carousel.

				var slider = $('.tm-img-slider');
				var windowWidth = $(window).width();

				if (slider.hasClass('slick-initialized')) {
					slider.slick('destroy');
				}

				if(windowWidth < 640) {
					slider.slick({
	              		dots: true,
	              		infinite: false,
	              		slidesToShow: 1,
	              		slidesToScroll: 1
	              	});
				}
				else if(windowWidth < 992) {
					slider.slick({
	              		dots: true,
	              		infinite: false,
	              		slidesToShow: 2,
	              		slidesToScroll: 1
	              	});
				}
				else {
					// Slick carousel
	              	slider.slick({
	              		dots: true,
	              		infinite: false,
	              		slidesToShow: 3,
	              		slidesToScroll: 2
	              	});
				}

				// Init Magnific Popup
				$('.tm-img-slider').magnificPopup({
				  delegate: 'a', // child items selector, by clicking on it popup will open
				  type: 'image',
				  gallery: {enabled:true}
				  // other options
				});
      		}
  		}

  		// Setup Nav
  		function setupNav() {
  			// Add Event Listener to each Nav item

  		}

  		function changePage(currentNavItem) {
  			// Update Nav items
  			$(".tm-main-nav a").removeClass("active");
     		currentNavItem.addClass("active");

	    	$(currentPageID).hide();

	    	// Show current page
	    	currentPageID = currentNavItem.data("page");
	    	$(currentPageID).fadeIn(1000);

	    	// Change background image
	    	var bgImg = currentNavItem.data("bgImg");
	    	$.backstretch("img/" + bgImg);
  		}

  		// Setup Nav Toggle Button
  		function setupNavToggle() {

			$("#tmMainNavToggle").on("click", function(){
				$(".sidebar").toggleClass("show");
			});
  		}

  		// If there is enough room, stick the footer at the bottom of page content.
  		// If not, place it after the page content
  		function setupFooter() {

  			var padding = 100;
  			var footerPadding = 40;
  			var mainContent = $("section"+currentPageID);
  			var mainContentHeight = mainContent.outerHeight(true);
  			var footer = $(".footer-link");
  			var footerHeight = footer.outerHeight(true);
  			var totalPageHeight = mainContentHeight + footerHeight + footerPadding + padding;
  			var windowHeight = $(window).height();

  			if(totalPageHeight > windowHeight){
  				$(".tm-content").css("margin-bottom", footerHeight + footerPadding + "px");
  				footer.css("bottom", footerHeight + "px");
  			}
  			else {
  				$(".tm-content").css("margin-bottom", "0");
  				footer.css("bottom", "20px");
  			}
  		}

  		// Everything is loaded including images.
      	$(window).on("load", function(){

      		// Render the page on modern browser only.
      		if(renderPage) {
				// Remove loader
		      	$('body').addClass('loaded');

		      	// Page transition
		      	var allPages = $(".tm-section");

		      	// Handle click of "Continue", which changes to next page
		      	// The link contains data-nav-link attribute, which holds the nav item ID
		      	// Nav item ID is then used to access and trigger click on the corresponding nav item
		      	var linkToAnotherPage = $("a.tm-btn[data-nav-link]");

			    if(linkToAnotherPage != null) {

			    	linkToAnotherPage.on("click", function(){
			    		var navItemToHighlight = linkToAnotherPage.data("navLink");
			    		$("a" + navItemToHighlight).click();
			    	});
			    }

		      	// Hide all pages
		      	allPages.hide();

		      	$("#tm-section-1").fadeIn();

		     	// Set up background first page
		     	var bgImg = $("#tmNavLink1").data("bgImg");

		     	$.backstretch("img/" + bgImg, {fade: 500});

		     	// Setup Carousel, Nav, and Nav Toggle
			    setupCarousel();
			    setupNav();
			    setupNavToggle();
			    setupFooter();

			    // Resize Carousel upon window resize
			    $(window).resize(function() {
			    	setupCarousel();
			    	setupFooter();
			    });
      		}
		});

		</script>
</body>
</html>

templates/menu.html
{% load static %}
{% load i18n %}
<!-- Sidebar -->
<div id="tmSideBar" class="col-xl-3 col-lg-4 col-md-12 col-sm-12 sidebar">

    <button id="tmMainNavToggle" class="menu-icon">&#9776;</button>

    <div class="inner">
        <center>
            <a href="/" style="margin-left:20px"><img src="{% static 'img/logo.png' %}" alt=""></a>
            <br>
            <br>

        </center>
        <center>
            <a href="callto:+380673040037">
                <h5>+38(067)304-00-37</h5>
            </a>
        </center>

        <nav id="tmMainNav" class="tm-main-nav">

            <ul>
                {% for item in menu %}
                <li>
                     <a href="/{{ item.title }}/" class="scrolly {% if item.id == active_href %} active{% endif %}" data-page="#tm-section-{{ item.id }}">
<!--                        {{ active_href }}-->
<!--                         {% if is_home %}+{% endif %}-->
                         <i class="fas fa-{{ item.img_name }} tm-nav-fa-icon"></i>
                        <span>{{ item.name }}</span>
                    </a>
                </li>
                {% endfor %}

            </ul>
        </nav>

         <center>
            <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
                <input name="next" type="hidden" value="/" />

                <select class="selectpicker" name="language" onchange="this.form.submit()">
                  {% get_current_language as LANGUAGE_CODE %}
                  {% get_available_languages as LANGUAGES %}
                  {% get_language_info_list for LANGUAGES as languages %}
                  {% for language in languages %}

                      <option
                        value="{{ language.code }}"
                        {% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}
                        >
                        {{ language.code }}
                      </option>

                  {% endfor %}
                </select>
            </form>
        </center>

    </div>
</div>